### PR TITLE
weavy: remove unused imports and frameworks

### PR DESCRIPTION
**Pull request by r-mckay**
This commit removes unused imports such as Foundation and ObjectiveC
from the Weavy files.

It also removes the unused dependencies concerning NSObject-Rx and
RxSwiftExt's pausable. Since these files are directly added in the
project there is no need to bootstrap them with Carthage anymore, or to
keep broken references.
However, in order to satisfy the licenses, the copyright and license
notices were added to the project.

### CODE REVIEW

**Comment by twittemb** [comment]
Hi @r-mckay 
I'm wondering why we should include dependencies licences from Repo we do not use. I have not copied/pasted files from their repo to Weavy (just copy/paste few lines of code).

It is true that these repos helped me or inspired me at some point. And for 2 of them I contributed to their code. Anyway, it is ok to reference them, but If we want to be fair, we should also mentioned this Licence: https://github.com/devxoul/RxViewController/blob/master/LICENSE

What's your opinion about that ?

**Comment by twittemb** [comment]
Hi @r-mckay 

I have amended your work on the Licenses by:
- adding a reference to the licenses in the source code
- adding the License for RxViewController in the DependenciesLicenses folder

I have also regenerated the documentation with Jazzy.

Is it OK with you ?

thx.

**Comment by r-mckay** [comment]
Hey,
could you also update the commit-msg to reflect all the additions you made please?
Thx!

**Comment by twittemb** [comment]
hi @r-mckay 

The commit message has been amended.

Since this was the only remaining issue, I will merge this PR.

Thanks for your work.

**Review by twittemb — APPROVED** [review]
hi @r-mckay

The commit message has been amended.

Since this was the only remaining issue, I will merge this PR.

Thanks for your work.

**Pull request merged**
